//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSims.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectSims.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string Adresa_ {
            get {
                return ResourceManager.GetString("Adresa:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere.
        /// </summary>
        internal static string BiloGde {
            get {
                return ResourceManager.GetString("BiloGde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Anytime/.
        /// </summary>
        internal static string BiloKad {
            get {
                return ResourceManager.GetString("BiloKad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anytime/Anywhere.
        /// </summary>
        internal static string BiloKadBiloGde {
            get {
                return ResourceManager.GetString("BiloKadBiloGde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days number:.
        /// </summary>
        internal static string BrojDana_ {
            get {
                return ResourceManager.GetString("BrojDana:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest number:.
        /// </summary>
        internal static string BrojGostiju_ {
            get {
                return ResourceManager.GetString("BrojGostiju:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bonus points left:.
        /// </summary>
        internal static string BrojPreostaihBonusPoena_ {
            get {
                return ResourceManager.GetString("BrojPreostaihBonusPoena:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reservations this year:.
        /// </summary>
        internal static string BrojRezervacijaOveGodine_ {
            get {
                return ResourceManager.GetString("BrojRezervacijaOveGodine:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness*:.
        /// </summary>
        internal static string Cistoca__ {
            get {
                return ResourceManager.GetString("Cistoca*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Dalje {
            get {
                return ResourceManager.GetString("Dalje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to forum!.
        /// </summary>
        internal static string DobroDosliNaForum {
            get {
                return ResourceManager.GetString("DobroDosliNaForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add accommodation images:.
        /// </summary>
        internal static string DodajteSlikeSmestaja_ {
            get {
                return ResourceManager.GetString("DodajteSlikeSmestaja:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Drzava_ {
            get {
                return ResourceManager.GetString("Drzava:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Grad_ {
            get {
                return ResourceManager.GetString("Grad:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose accommodation to rate.
        /// </summary>
        internal static string Izaberite_smestaj_za_ocenjivanje {
            get {
                return ResourceManager.GetString("Izaberite smestaj za ocenjivanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose accommodation to rate.
        /// </summary>
        internal static string IzaberiteSmestajZaOcenjivanje {
            get {
                return ResourceManager.GetString("IzaberiteSmestajZaOcenjivanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left comment:.
        /// </summary>
        internal static string jePostavioKomentar_ {
            get {
                return ResourceManager.GetString("jePostavioKomentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Komentar_ {
            get {
                return ResourceManager.GetString("Komentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment from owner of accommodation.
        /// </summary>
        internal static string KomentarVlasnikaSmestaja {
            get {
                return ResourceManager.GetString("KomentarVlasnikaSmestaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner correctness*:.
        /// </summary>
        internal static string KorektnostVlasnika__ {
            get {
                return ResourceManager.GetString("KorektnostVlasnika*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string KorisnickoIme_ {
            get {
                return ResourceManager.GetString("KorisnickoIme:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search end date:.
        /// </summary>
        internal static string KrajnjiDatumPretrage_ {
            get {
                return ResourceManager.GetString("KrajnjiDatumPretrage:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Lokacija_ {
            get {
                return ResourceManager.GetString("Lokacija:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location*:.
        /// </summary>
        internal static string Lokacija__ {
            get {
                return ResourceManager.GetString("Lokacija*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of guests:.
        /// </summary>
        internal static string MaksimalanBrojGostiju_ {
            get {
                return ResourceManager.GetString("MaksimalanBrojGostiju:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string MejlAdresa_ {
            get {
                return ResourceManager.GetString("MejlAdresa:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min number of days:.
        /// </summary>
        internal static string MinimalanBrojDana_ {
            get {
                return ResourceManager.GetString("MinimalanBrojDana:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        internal static string MojeRezervacije {
            get {
                return ResourceManager.GetString("MojeRezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ratings.
        /// </summary>
        internal static string MojiUtisci {
            get {
                return ResourceManager.GetString("MojiUtisci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My requests.
        /// </summary>
        internal static string MojiZahtevi {
            get {
                return ResourceManager.GetString("MojiZahtevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My comment for accommodation.
        /// </summary>
        internal static string MojKomentarZaSmestaj {
            get {
                return ResourceManager.GetString("MojKomentarZaSmestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string MojNalog {
            get {
                return ResourceManager.GetString("MojNalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my forums.
        /// </summary>
        internal static string NadjiMojeForume {
            get {
                return ResourceManager.GetString("NadjiMojeForume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Nazad {
            get {
                return ResourceManager.GetString("Nazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Naziv_ {
            get {
                return ResourceManager.GetString("Naziv:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation urgency:.
        /// </summary>
        internal static string NivoHitnostiRenoviranja_ {
            get {
                return ResourceManager.GetString("NivoHitnostiRenoviranja:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Obavestenja {
            get {
                return ResourceManager.GetString("Obavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string Ocene {
            get {
                return ResourceManager.GetString("Ocene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Oceni {
            get {
                return ResourceManager.GetString("Oceni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate accommodation.
        /// </summary>
        internal static string OceniteSmestaj {
            get {
                return ResourceManager.GetString("OceniteSmestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating accommodation.
        /// </summary>
        internal static string OcenjivanjeSmestaja {
            get {
                return ResourceManager.GetString("OcenjivanjeSmestaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string OdjaviSe {
            get {
                return ResourceManager.GetString("OdjaviSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave comment:.
        /// </summary>
        internal static string OstaviteKomentar_ {
            get {
                return ResourceManager.GetString("OstaviteKomentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled reservations.
        /// </summary>
        internal static string OtkazaneRezervacije {
            get {
                return ResourceManager.GetString("OtkazaneRezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Otkazi {
            get {
                return ResourceManager.GetString("Otkazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        internal static string OtkazivanjeRezervacije {
            get {
                return ResourceManager.GetString("OtkazivanjeRezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search start date:.
        /// </summary>
        internal static string PocetniDatumPretrage_ {
            get {
                return ResourceManager.GetString("PocetniDatumPretrage:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Pokreni {
            get {
                return ResourceManager.GetString("Pokreni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new forum.
        /// </summary>
        internal static string PokreniNoviForum {
            get {
                return ResourceManager.GetString("PokreniNoviForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new forum.
        /// </summary>
        internal static string PokreniteNoviForum {
            get {
                return ResourceManager.GetString("PokreniteNoviForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation date change.
        /// </summary>
        internal static string PomeranjeRezervacije {
            get {
                return ResourceManager.GetString("PomeranjeRezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Pomoc {
            get {
                return ResourceManager.GetString("Pomoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Postavi {
            get {
                return ResourceManager.GetString("Postavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed information.
        /// </summary>
        internal static string PotrebneInformacije {
            get {
                return ResourceManager.GetString("PotrebneInformacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation recommendation ( optional ).
        /// </summary>
        internal static string PreporukaZaRenoviranje {
            get {
                return ResourceManager.GetString("PreporukaZaRenoviranje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation recommendations:.
        /// </summary>
        internal static string PreporukeZaRenoviranje_ {
            get {
                return ResourceManager.GetString("PreporukeZaRenoviranje:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Preskoci {
            get {
                return ResourceManager.GetString("Preskoci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Pretraga {
            get {
                return ResourceManager.GetString("Pretraga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find dates.
        /// </summary>
        internal static string PretraziDatume {
            get {
                return ResourceManager.GetString("PretraziDatume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show forum.
        /// </summary>
        internal static string PrikaziForum {
            get {
                return ResourceManager.GetString("PrikaziForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show everything.
        /// </summary>
        internal static string PrikaziSve {
            get {
                return ResourceManager.GetString("PrikaziSve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ratings.
        /// </summary>
        internal static string PrikazOcena {
            get {
                return ResourceManager.GetString("PrikazOcena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation reservation.
        /// </summary>
        internal static string RezervacijaSmestaja {
            get {
                return ResourceManager.GetString("RezervacijaSmestaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm reservation.
        /// </summary>
        internal static string Rezervisi {
            get {
                return ResourceManager.GetString("Rezervisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissal days:.
        /// </summary>
        internal static string RokZaOtkazivanje_ {
            get {
                return ResourceManager.GetString("RokZaOtkazivanje:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What if super guest.
        /// </summary>
        internal static string StaJeSuperGost {
            get {
                return ResourceManager.GetString("StaJeSuperGost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TipSmestaja_ {
            get {
                return ResourceManager.GetString("TipSmestaja:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave question or comment:.
        /// </summary>
        internal static string UnesitePitanjeIliKomentar_ {
            get {
                return ResourceManager.GetString("UnesitePitanjeIliKomentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ratings.
        /// </summary>
        internal static string UtisciVlasnika {
            get {
                return ResourceManager.GetString("UtisciVlasnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Uvezi {
            get {
                return ResourceManager.GetString("Uvezi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very useful.
        /// </summary>
        internal static string VeomaKoristan {
            get {
                return ResourceManager.GetString("VeomaKoristan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for money*:.
        /// </summary>
        internal static string VrednostZaNovac__ {
            get {
                return ResourceManager.GetString("VrednostZaNovac*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active reservations.
        /// </summary>
        internal static string ZakazaneRezervacije {
            get {
                return ResourceManager.GetString("ZakazaneRezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close forum.
        /// </summary>
        internal static string ZatvoriForum {
            get {
                return ResourceManager.GetString("ZatvoriForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish rating accommodation.
        /// </summary>
        internal static string ZavrsiOcenjivanjeSmestaja {
            get {
                return ResourceManager.GetString("ZavrsiOcenjivanjeSmestaja", resourceCulture);
            }
        }
    }
}
