//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSims.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectSims.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string Adresa_ {
            get {
                return ResourceManager.GetString("Adresa:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere.
        /// </summary>
        internal static string Bilo_gde {
            get {
                return ResourceManager.GetString("Bilo gde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Anytime/.
        /// </summary>
        internal static string Bilo_kad_ {
            get {
                return ResourceManager.GetString("Bilo kad/", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anytime/Anywhere.
        /// </summary>
        internal static string Bilo_kad_Bilo_gde {
            get {
                return ResourceManager.GetString("Bilo kad/Bilo gde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Number of days:.
        /// </summary>
        internal static string Broj_dana_ {
            get {
                return ResourceManager.GetString("Broj dana:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        internal static string Broj_gostiju_ {
            get {
                return ResourceManager.GetString("Broj gostiju:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bonus points left:.
        /// </summary>
        internal static string Broj_preostaih_bonus_poena_ {
            get {
                return ResourceManager.GetString("Broj preostaih bonus poena:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reservations this year:.
        /// </summary>
        internal static string Broj_rezervacija_ove_godine_ {
            get {
                return ResourceManager.GetString("Broj rezervacija ove godine:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness*:.
        /// </summary>
        internal static string Cistoca__ {
            get {
                return ResourceManager.GetString("Cistoca*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Dalje {
            get {
                return ResourceManager.GetString("Dalje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to forum!.
        /// </summary>
        internal static string Dobro_dosli_na_forum_ {
            get {
                return ResourceManager.GetString("Dobro dosli na forum!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add accommodation images:.
        /// </summary>
        internal static string Dodajte_slike_smestaja_ {
            get {
                return ResourceManager.GetString("Dodajte slike smestaja:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Drzava_ {
            get {
                return ResourceManager.GetString("Drzava:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Grad_ {
            get {
                return ResourceManager.GetString("Grad:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose accommodation to rate.
        /// </summary>
        internal static string Izaberite_smestaj_za_ocenjivanje {
            get {
                return ResourceManager.GetString("Izaberite smestaj za ocenjivanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left comment:.
        /// </summary>
        internal static string je_postavio_la_komentar_ {
            get {
                return ResourceManager.GetString("je postavio/la komentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Komentar_ {
            get {
                return ResourceManager.GetString("Komentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment from owner of accommodation.
        /// </summary>
        internal static string Komentar_vlasnika_smestaja {
            get {
                return ResourceManager.GetString("Komentar vlasnika smestaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner correctness*:.
        /// </summary>
        internal static string Korektnost_vlasnika__ {
            get {
                return ResourceManager.GetString("Korektnost vlasnika*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Korisnicko_ime_ {
            get {
                return ResourceManager.GetString("Korisnicko ime:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search end date:.
        /// </summary>
        internal static string Krajnji_datum_pretrage_ {
            get {
                return ResourceManager.GetString("Krajnji datum pretrage:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Lokacija_ {
            get {
                return ResourceManager.GetString("Lokacija:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location*:.
        /// </summary>
        internal static string Lokacija__ {
            get {
                return ResourceManager.GetString("Lokacija*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of guests:.
        /// </summary>
        internal static string Maksimalan_broj_gostiju_ {
            get {
                return ResourceManager.GetString("Maksimalan broj gostiju:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string Mejl_adresa_ {
            get {
                return ResourceManager.GetString("Mejl adresa:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min number of days:.
        /// </summary>
        internal static string Minimalan_broj_dana_ {
            get {
                return ResourceManager.GetString("Minimalan broj dana:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My comment for accommodation.
        /// </summary>
        internal static string Moj_komentar_za_smestaj {
            get {
                return ResourceManager.GetString("Moj komentar za smestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string Moj_nalog {
            get {
                return ResourceManager.GetString("Moj nalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        internal static string Moje_rezervacije {
            get {
                return ResourceManager.GetString("Moje rezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ratings.
        /// </summary>
        internal static string Moji_utisci {
            get {
                return ResourceManager.GetString("Moji utisci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My requests.
        /// </summary>
        internal static string Moji_zahtevi {
            get {
                return ResourceManager.GetString("Moji zahtevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my forums.
        /// </summary>
        internal static string Nadji_moje_forume {
            get {
                return ResourceManager.GetString("Nadji moje forume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Nazad {
            get {
                return ResourceManager.GetString("Nazad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Naziv_ {
            get {
                return ResourceManager.GetString("Naziv:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation urgency:.
        /// </summary>
        internal static string Nivo_hitnosti_renoviranja_ {
            get {
                return ResourceManager.GetString("Nivo hitnosti renoviranja:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Obavestenja {
            get {
                return ResourceManager.GetString("Obavestenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Oceni {
            get {
                return ResourceManager.GetString("Oceni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate accommodation.
        /// </summary>
        internal static string Ocenite_smestaj {
            get {
                return ResourceManager.GetString("Ocenite smestaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating accommodation.
        /// </summary>
        internal static string Ocenjivanje_smestaja {
            get {
                return ResourceManager.GetString("Ocenjivanje smestaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Odjavi_se {
            get {
                return ResourceManager.GetString("Odjavi se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Odustani {
            get {
                return ResourceManager.GetString("Odustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave comment:.
        /// </summary>
        internal static string Ostavite_komentar_ {
            get {
                return ResourceManager.GetString("Ostavite komentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled reservations.
        /// </summary>
        internal static string Otkazane_rezervacije {
            get {
                return ResourceManager.GetString("Otkazane rezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Otkazi {
            get {
                return ResourceManager.GetString("Otkazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        internal static string Otkazivanje_rezervacije {
            get {
                return ResourceManager.GetString("Otkazivanje rezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search start date:.
        /// </summary>
        internal static string Pocetni_datum_pretrage_ {
            get {
                return ResourceManager.GetString("Pocetni datum pretrage:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Pokreni {
            get {
                return ResourceManager.GetString("Pokreni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new forum.
        /// </summary>
        internal static string Pokreni_novi_forum {
            get {
                return ResourceManager.GetString("Pokreni novi forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new forum.
        /// </summary>
        internal static string Pokrenite_novi_forum {
            get {
                return ResourceManager.GetString("Pokrenite novi forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation date change.
        /// </summary>
        internal static string Pomeranje_rezervacije {
            get {
                return ResourceManager.GetString("Pomeranje rezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Pomoc {
            get {
                return ResourceManager.GetString("Pomoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Postavi {
            get {
                return ResourceManager.GetString("Postavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed information.
        /// </summary>
        internal static string Potrebne_informacije {
            get {
                return ResourceManager.GetString("Potrebne informacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation recommendation ( optional ).
        /// </summary>
        internal static string Preporuka_za_renoviranje___opciono__ {
            get {
                return ResourceManager.GetString("Preporuka za renoviranje ( opciono )", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation recommendations:.
        /// </summary>
        internal static string Preporuke_za_renoviranje_ {
            get {
                return ResourceManager.GetString("Preporuke za renoviranje:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Preskoci {
            get {
                return ResourceManager.GetString("Preskoci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Pretraga {
            get {
                return ResourceManager.GetString("Pretraga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find dates.
        /// </summary>
        internal static string Pretrazi_datume {
            get {
                return ResourceManager.GetString("Pretrazi datume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ratings.
        /// </summary>
        internal static string Prikaz_ocena {
            get {
                return ResourceManager.GetString("Prikaz ocena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show forum.
        /// </summary>
        internal static string Prikazi_forum {
            get {
                return ResourceManager.GetString("Prikazi forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show everything.
        /// </summary>
        internal static string Prikazi_sve {
            get {
                return ResourceManager.GetString("Prikazi sve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation reservation.
        /// </summary>
        internal static string Rezervacija_smestaja {
            get {
                return ResourceManager.GetString("Rezervacija smestaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm reservation.
        /// </summary>
        internal static string Rezervisi {
            get {
                return ResourceManager.GetString("Rezervisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissal days:.
        /// </summary>
        internal static string Rok_za_otkazivanje_ {
            get {
                return ResourceManager.GetString("Rok za otkazivanje:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What if super guest.
        /// </summary>
        internal static string Sta_je_super_gost {
            get {
                return ResourceManager.GetString("Sta je super gost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation type:.
        /// </summary>
        internal static string Tip_smestaja_ {
            get {
                return ResourceManager.GetString("Tip smestaja:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave question or comment:.
        /// </summary>
        internal static string Unesite_pitanje_ili_komentar_ {
            get {
                return ResourceManager.GetString("Unesite pitanje ili komentar:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ratings.
        /// </summary>
        internal static string Utisci_vlasnika {
            get {
                return ResourceManager.GetString("Utisci vlasnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Uvezi {
            get {
                return ResourceManager.GetString("Uvezi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very useful.
        /// </summary>
        internal static string Veoma_koristan {
            get {
                return ResourceManager.GetString("Veoma koristan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for money*:.
        /// </summary>
        internal static string Vrednost_za_novac__ {
            get {
                return ResourceManager.GetString("Vrednost za novac*:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active reservations.
        /// </summary>
        internal static string Zakazane_rezervacije {
            get {
                return ResourceManager.GetString("Zakazane rezervacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close forum.
        /// </summary>
        internal static string Zatvori_forum {
            get {
                return ResourceManager.GetString("Zatvori forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish rating accommodation.
        /// </summary>
        internal static string Zavrsi_ocenjivanje_smestaja {
            get {
                return ResourceManager.GetString("Zavrsi ocenjivanje smestaja", resourceCulture);
            }
        }
    }
}
